### ISSUE TITLE
rgb data from img file

### ISSUE THREAD

**Issue by FrancescaCi** [itchencheng/hdrnet-mobile#7]
Hi guys, 
I have some problems for reading the data images, in particular at this point:

ret = (*f_HDRNET_read_uchar_data_from_file)(rgb_data, size, input_file);

because there is not any .rgb file. In fact, the error is:

Error: fread failed! read_data_from_file

Am I missing some points? a conversion from original image to raw .rgb data?

Thank you in advance for you support!

**Comment by techxzen** [comment]
Please refer to the python script "script/run.py", which contains a process converting jpeg to rgb raw file.

**Comment by FrancescaCi** [comment]
Thank you for the support!

**Comment by itchencheng** [comment]
Please refer to the python script "script/run.py", which contains a process converting jpeg to rgb raw file.
